### ISSUE TITLE
TM2: abbreviation in HTML is expanded into CSS instead

### ISSUE THREAD

**Issue by kaelig** [emmetio/Emmet.tmplugin#9]
In an HTML file, 

`div.class`

Is expanded into:
`display: .class;`

Which makes Emmet unusable in TextMate 2.

Is there anything I can do?
##

**Comment by uanwar88** [comment]
I am also having the same problem. Have there been any fixes to this? It only happens after you save a new file as an html file. It seems to work as long as the file extension is not *.html.

**Comment by danealexander** [comment]
I've had this problem when my html files are inside a folder that has 'css' in the name. For example html files inside a folder called 'css-concepts' will have this issue. Removing css from the folder name fixes the issue.

**Comment by kaelig** [comment]
Closing this as it's super old.
